### ISSUE TITLE
Add the ldap capability on the hello page.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-ldap#2]
```
"ldap": {
    "url": "https://github.com/mozilla-services/kinto-ldap",
    "description": "Basic Auth user are validated against an LDAP server."
},
```

**Comment by Natim** [comment]
It will more or less look like that: https://github.com/Kinto/kinto-changes/pull/10

**Comment by lavish205** [comment]
can we use `add_api_capability` method for `config` object in [kinto-ldap/__init__.py](https://github.com/Kinto/kinto-ldap/blob/master/kinto_ldap/__init__.py) file.

**Comment by Natim** [comment]
Yes
